### ISSUE TITLE
Fix doc generation

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/NearestNeighborModels.jl#44]
Doc tests are failing: https://github.com/JuliaAI/NearestNeighborModels.jl/pull/43/checks?check_run_id=3100646324

@OkonSamuel Any chance you could investigate?

**Comment by OkonSamuel** [comment]
@ablaom doctest failure has been fixed. see [here](https://github.com/JuliaAI/NearestNeighborModels.jl/commit/5c12ab912ca10391cd4e6cf2c0f8324148c448e4)

Should I go ahead and tag a new release or would you do that yourself?

**Comment by ablaom** [comment]
You can make a release if you'd like. I don't normally bother for a documentation fix.
